// <auto-generated />
using System;
using CategoriesService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CategoriesService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250525125541_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoriesService.Models.DanhMuc", b =>
                {
                    b.Property<int>("IDDanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("CapDanhMuc")
                        .HasColumnType("int");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("bit");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDDanhMuc");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("CategoriesService.Models.HinhAnhDanhMuc", b =>
                {
                    b.Property<int>("IDHinhAnhDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDHinhAnhDanhMuc"));

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDDanhMuc")
                        .HasColumnType("int");

                    b.HasKey("IDHinhAnhDanhMuc");

                    b.HasIndex("IDDanhMuc");

                    b.ToTable("HinhAnhDanhMucs");
                });

            modelBuilder.Entity("CategoriesService.Models.SanPham", b =>
                {
                    b.Property<string>("IDSanPham")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDCuaHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDDanhMuc")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDSanPham");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("CategoriesService.Models.HinhAnhDanhMuc", b =>
                {
                    b.HasOne("CategoriesService.Models.DanhMuc", "DanhMuc")
                        .WithMany("HinhAnhDanhMucs")
                        .HasForeignKey("IDDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("CategoriesService.Models.DanhMuc", b =>
                {
                    b.Navigation("HinhAnhDanhMucs");
                });
#pragma warning restore 612, 618
        }
    }
}
